apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-visa-deployment
  labels:
    app: usvisa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usvisa
  template:
    metadata:
      labels:
        app: usvisa
    spec:
      containers:
      - name: scheduler
        image: gcr.io/seven-exp/usvisa
        env: 
        - name: PYTHONUNBUFFERED
          value: "1"
